FORMAT: 1A

# Desasehat API

# Group Pasien

## List Pasien [/pasien]

### List Pasien [GET]
+ Response 200 (application/json)

    + Body

            {
                "id": 1,
                "name": "Mahesa Novianto",
                "disease_type": "Diabetes Mellitus",
                "village_id": {
                    "id": 1,
                    "name": "Condong Catur",
                    "kecamatan": "Depok",
                    "kabupaten": "Sleman",
                    "provinsi": "DI Yogyakarta"
                },
                "age": 52
            }
            
## Detail Pasien [/pasien/{id}]

+ Parameters

    + id: 1 (number) - id pasien.

### Detail Pasien [GET]

+ Response 200 (application/json)

    + Body

            {
              "id": 1,
              "name": "Mahesa Novianto",
              "address": "Jl. Rasuna Said No. 89",
              "phone": "672.418.5626",
              "pob": "Klaten",
              "dob": "04-08-1965",
              "gender": "perempuan",
              "blood_type": "A",
              "picture": null,
              "description": null,
              "disease_type": "Diabetes Mellitus",
              "status": "accepted",
              "village_id": {
              "id": 1,
              "name": "Condong Catur",
              "kecamatan": "Depok",
              "kabupaten": "Sleman",
              "provinsi": "DI Yogyakarta"
              },
              "user_id": {
              "id": 1,
              "name": "Dimas"
              },
              "created_at": "2018-04-03T05:37:36.957Z",
              "updated_at": "2018-04-03T05:37:36.957Z",
              "age": 52
            }



# Group Desa

## List Desa [/desa]

### List Desa [GET]

+ Response 200 (application/json)

    + Body

            [
              {
                  "id": 1,
                  "name": "Condong Catur",
                  "kecamatan": "Depok",
                  "kabupaten": "Sleman",
                  "provinsi": "DI Yogyakarta"
              },
              {
                  "id": 2,
                  "name": "Catur Tunggal",
                  "kecamatan": "Depok",
                  "kabupaten": "Sleman",
                  "provinsi": "DI Yogyakarta"
              }
            ]

        
        
## List Detail Desa [/desa/{id}]

+ Parameters

    + id: 1 (number) - id desa.

### List Detail Desa [GET]

+ Response 200 (application/json)

    + Body

            {
              "id": 1,
              "name": "Condong Catur",
              "kecamatan": "Depok",
              "kabupaten": "Sleman",
              "provinsi": "DI Yogyakarta",
              "description": "Kodepos 55283",
              "created_at": "2018-04-03T05:37:36.264Z",
              "updated_at": "2018-04-03T05:37:36.264Z"
            }
        
        
# Group Edukasi

## List Edukasi [/edukasi]

### List Edukasi [GET]

+ Response 200 (application/json)

    + Body

              [
                {
                    "id": 1,
                    "title": "Artikel Edukasi",
                    "picture": {
                        "url": "/uploads/article/picture/1/picture.png"
                    },
                    "created_at": "2018-04-03T05:37:36.347Z"
                },
                {
                    "id": 2,
                    "title": "Artikel Edukasi",
                    "picture": {
                        "url": "/uploads/article/picture/1/picture.png"
                    },
                    "created_at": "2018-04-03T05:37:36.347Z"
                }
              ]


## List Detail Edukasi [/edukasi/{id}]

+ Parameters

    + id: 1 (number) - id edukasi.

### List Detail Edukasi [GET]

+ Response 200 (application/json)

    + Body

            {
                "id": 1,
                "title": "Artikel Edukasi",
                "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempus faucibus malesuada. Fusce condimentum dolor a tortor cursus, pulvinar varius nisl placerat. Vivamus gravida libero et quam blandit, non lobortis risus aliquet. Vestibulum augue felis, auctor quis euismod vitae, vehicula eget nulla. Ut ut rhoncus justo, sed vehicula felis. Aenean semper ipsum consequat, mollis tortor at, ornare lectus. Morbi faucibus et odio eu volutpat. Integer eleifend purus consectetur dolor tempus, eu egestas augue volutpat. Fusce vitae urna justo. Fusce quis leo condimentum urna pellentesque varius eget ac elit. Quisque quis elit sit amet magna scelerisque porta ac semper tellus. Donec vestibulum rutrum risus, vitae viverra metus feugiat nec. Duis rutrum viverra tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum ac ex gravida, volutpat turpis et, porttitor odio. Sed mollis vulputate  lorem et iaculis.",
                "picture": {
                    "url": "/uploads/article/picture/1/picture.png"
                },
                "created_at": "2018-04-03T05:37:36.347Z"
            }